### ISSUE TITLE
Why does flow vars not available for task publish expressions?

### ISSUE THREAD

**Issue by orius123** [openscore/score-language#102]
when writing a flow I cannot access a flow var in the task `publish` statement.

for example:

```yaml
flow:
  inputs:
    - input: 1
  workflow:
    some_task:
      ...
      publish:
        - new_var: input + 1
```
new output will be empty instead of `2`
