### ISSUE TITLE
produce outputs based on results

### ISSUE THREAD

**Issue by Bonczidai** [openscore/score-language#106]
We have situations when we want to produce certain outputs based on flow results - e.g. we want to produce output1 only if flow ends with SUCCESS, output2 only if flow ends with LONG_NASTY_CONDITION_RESULT, otherwise they need to be empty.
 
 Now:
  ```
  outputs:
    - output1: returnResult if (returnCode == '0' and (not 'ERROR' in STDERR)) else ''
    - output2: STDOUT if returnCode == '0' and (not 'ERROR' in STDERR) and (...) else ''
    - normal_output:  normalOutput
  results:
    - SUCCESS: returnCode == '0' and (not 'ERROR' in STDERR)
    - LONG_NASTY_CONDITION_RESULT: returnCode == '0' and (not 'ERROR' in STDERR) and (...)
    - FAILURE
```

Now we have lots of code (condition) duplication. We could define some built-in mechanism for this - e.g:

  ```
  outputs:
    - output1: 
        expression: returnResult
        produced_on: SUCCESS 
    - output2:
        expression: STDOUT
        produced_on: LONG_NASTY_CONDITION_RESULT 
    - normal_output:  normalOutput
  results:
    - SUCCESS: returnCode == '0' and (not 'ERROR' in STDERR)
    - LONG_NASTY_CONDITION_RESULT: returnCode == '0' and (not 'ERROR' in STDERR) and (...)
    - FAILURE
```

Do we want to implement something similar to this?
@meirwah @oritstone @orius123
