### ISSUE TITLE
Boolean outputs published as ints

### ISSUE THREAD

**Issue by SamMarkowitz** [openscore/score-language#134]
Given the following flow:

```yaml
namespace: code-examples.test

imports:
  ops: code-examples.test

flow:
  name: test
  workflow:
    - task:
        do:
          ops.operation:
        publish:
          - var: out
    - print_it:
        do:
          ops.print:
            - text: var
```

and operation:

```yaml
namespace: code-examples.test

operation:
  name: operation
  action:
    python_script: |
      b = 2 == 2
  outputs:
    - out: b
```

Expected to be printed: `True` 
Actually printed: `1`
