### ISSUE TITLE
"Flow finished with result" for non-SUCCESS/FAILURE

### ISSUE THREAD

**Issue by SamMarkowitz** [openscore/score-language#26]
If the result of a flow is not SUCCESS or FAILURE the CLI does not display the line "Flow: flow_x finished with result :".

**Comment by SamMarkowitz** [comment]
Flow
```yaml
workflow:
    test:
      do:
        ops.funky_result:
```

Operation
```yaml
- funky_result:
      action:
        python_script: print 'The result will be funky.'
      results:
        - FUNKY: 1 == 1
```

There is no  matching navigation in the task.
