### ISSUE TITLE
Flow results - Compiler error handling

### ISSUE THREAD

**Issue by SamMarkowitz** [openscore/score-language#27]
The Sublime snippet has a spot for flow results:
```yaml
flow:
      name: flow name - {sub.sl}
      # inputs:
      workflow:
      # outputs:
      # results:
```
Attempting to use `results` the CLI gives you this: `Command failed java.lang.RuntimeException: java.lang.NullPointerException`.

Currently, a subflow can pass it's results to its superflow in the usual manner: by the results/navigation of the final task (this itself only works for `SUCCESS` and `FAILURE`, but not other results).

**Comment by oritstone** [comment]
@SamMarkowitz  Isn't it exactly the same issue as #26 ?

**Comment by SamMarkowitz** [comment]
Not quite, but they certainly may be related. 

#26  - Everything *runs smoothly*, however the result is not displayed on completion of the flow. (This is probably the same problem as the side point in #27 that a subflow can only have a result of `SUCCESS` or `FAILURE`)

#27 - When explicitly trying to return a result from a flow
```yaml
flow:
  name: flow_name
  workflow:
    ...
  results:
    - SUCCESS: 1 == 1
```
it *crashes* you get a `NullPointerException` even when the result is a `SUCCESS` or `FAILURE`.

**Comment by SamMarkowitz** [comment]
Example:

Flow:

```yaml
flow:
  name: my_flow

  workflow:
    test:
      do:
        ops.print:
          - text: "'Test'"
  results:
    - SUCCESS
```

Operation
```yaml
- print:
      inputs:
        - text
      action:
        python_script: print text
```
