### ISSUE TITLE
Step input assignments ignored when overridding existing variables?

### ISSUE THREAD

**Issue by zsolt-donca-hp** [openscore/score-language#58]
It seems like input assignments on steps are ignored when there a flow input with the same name as the step input. Check the following modified hello-world application:

    namespace: user.examples.hello_world

    imports:
      ops: user.examples.hello_world

    flow:
      name: hello_world
      inputs:
        - text1
        - text2
        - text3
      workflow:
        sayHi:
          do:
            ops.print:
              - text1: text3
              - text2: text3

with the corresponding 'print' operation:

    namespace: user.examples.hello_world

    operations:
      - print:
          inputs:
            - text1
            - text2
          action:
            python_script: print text1, text2
          results:
            - SUCCESS

When running with the arguments --i text1=Hello,text2=World,text3=Unrelated, I would expect it to print "Unrelated Unrelated", but instead, it seems to print "Hello World":

    slang>run --f c:\Work\hackaton\stuff\hello_world.sl --i text1=Hello,text2=World,text3=Unrelated
    - sayHi
    Hello World
    Flow : hello_world finished with result : SUCCESS
    Flow execution time took  0:00:00.411 , with execution id : 101600729

**Comment by avimora** [comment]
This is the behavior by design: the context will take precedence by default unless explicitly specified that the input is not overridable

**Comment by zsolt-donca-hp** [comment]
I must say that I find this a very counter-intuitive default behavior; this behavior was not clear even to our seasoned slang-developer Tudor. :) 

Can you give me an example on how to modify the above code to make it work, without changing the variable names?

**Comment by avimora** [comment]
I agree, it seems somehow confusing at first glance :)
In your example you don't need `text1` & `text2` as flow input, just omit them.
When dealing with inputs you can do the following:
```yaml
  inputs:
    - text1:
        default: text3
        overridable: false
```

**Comment by oritstone** [comment]
@zsolt-donca-hp - if you don't want to override the inputs names, why do you want the inputs of the file & the inputs of the task to have the same names?

**Comment by meirwah** [comment]
do we think this is a bug ? or can i close this?

**Comment by zsolt-donca-hp** [comment]
I'm not convinced; I would suggest us setting up a meeting to talk about this.

**Comment by oritstone** [comment]
You have an ability to specify that you do not want an input to be overridable, meaning, that it would get its value from the given default value, and not from the flow context.
For example in your example above, you can write it like this:
```yaml
flow:
  name: hello_world
  inputs:
    - text1
    - text2
    - text3
  workflow:
    - sayHi:
        do:
          ops.print:
            - text1: 
                default: text3
                overridable: false
            - text2: 
                default: text3
                overridable: false
```
In this case, with the running example given above, it will print: `Unrelated Unrelated` as you expected.
@zsolt-donca-hp , do you think it is an acceptable solution? Is it clear enough?
