### ISSUE TITLE
Have an officially documented support for using external Python libraries

### ISSUE THREAD

**Issue by zsolt-donca-hp** [openscore/score-language#59]
In order to use external Python libraries in your Slang operations' python scripts, you must edit slang.bat, and add the argument -Dpython.path=<path> to the line invoking java.exe, pointing to a path where your (extracted) Python libraries are located at. Figuring this out yourself and "hacking" slang.bat is fine for a hackaton, but not a very nice end-user experience. 

I would suggest adding a documented optional argument to slang.bat to set this property, so the user wouldn't need to edit the file.

**Comment by meirwah** [comment]
@orius123 any way we can make dynamic? as part of the appassembler?

**Comment by orius123** [comment]
According to appasembler docs, Making it get the value from an environment variable seems pretty easy.

**Comment by orius123** [comment]
I will go over jython docs to see if there is any convention.

**Comment by okitac** [comment]
Importing in the python op itself does seem to work for *.py imports (*.pyc imports are obviously going to have their own set of issues), although I haven't done much beyond verify that it's possible to import thusly:

```yaml
namespace: user.examples.hello_world_imports

operations:
  - print_imports:
      inputs:
        - text
      action:
        python_script: |
          import sys
          print sys.path
          sys.path.append('/usr/local/home/cat/.local/lib/python2.7/site-packages/jhbuild')
          print sys.path
          import monkeypatch
          print monkeypatch.__file__
          print text
      results:
        - SUCCESS
```
```
slang>run hello_world_imports.sl
- sayHi
['/usr/local/src/projects/openscore/score-lang-cli/slang/lib/Lib', '/usr/local/src/projects/openscore/score-lang-cli/slang/lib/jython-standalone-2.7-b3.jar/Lib', '__classpath__', '__pyclasspath__/']
['/usr/local/src/projects/openscore/score-lang-cli/slang/lib/Lib', '/usr/local/src/projects/openscore/score-lang-cli/slang/lib/jython-standalone-2.7-b3.jar/Lib', '__classpath__', '__pyclasspath__/', '/usr/local/home/cat/.local/lib/python2.7/site-packages/jhbuild']
/usr/local/home/cat/.local/lib/python2.7/site-packages/jhbuild/monkeypatch$py.class
Hello, World
Flow : hello_world_imports finished with result : SUCCESS
Flow execution time took  0:00:00.489 , with execution id : 101600001
```
