### ISSUE TITLE
slang-cli documentation does not mention requirement for whitespace/indentation and error messages are unhelpful

### ISSUE THREAD

**Issue by okitac** [openscore/score-language#81]
The slang-cli documentation doesn't mention that slang is left hand side whitespace indentation sensitive, or that tabs aren't considered to be valid whitespace.  This is both important to know, and potentially frustrating, as the error messages aren't always helpful:

(1) The error message below comes from breaking the indentation model, and the error actually points to the line after the problem indentation:
```yaml
namespace: user.examples.hello_world-s

imports:
  ops: user.examples.hello_world-s

flow:
  name: hello_world-s
  workflow:
    sayHi:
      do:
ops.print:
          - text: "'Hello, World'"
```
```
slang>run hello_world-s.sl
Command failed java.lang.RuntimeException: java.lang.RuntimeException: There was a problem parsing the YAML source: hello_world-s.sl.
Cannot create property=ops.print for JavaBean=org.openscore.lang.compiler.model.ParsedSlang@51a9d2a5
 in 'string', line 1, column 1:
    namespace: user.examples.hello_w ... 
    ^
Unable to find property 'ops.print' on class: org.openscore.lang.compiler.model.ParsedSlang
 in 'string', line 12, column 11:
              - text: "'Hello, World'"
```

(2) This error is the result of failing to indent between do: and ops.print -- and the error doesn't provide the line number where things went sideways, or indicate that there's an indentation error, vs an issue with the property.
```yaml
namespace: user.examples.hello_world-s

imports:
  ops: user.examples.hello_world-s

flow:
  name: hello_world-s
  workflow:
    sayHi:
      do:
      ops.print:
          - text: "'Hello, World'"
```
```
slang>run hello_world-s.sl
Command failed java.lang.RuntimeException: java.lang.RuntimeException: Error compiling source: hello_world-s.sl. Property: ops.print at: sayHi is illegal
```
Note that (1) and (2) are both indentation erorrs, but produce notably different error messages.

(3) The following error comes from using tabs for whitespace, and while surprising, at least allows for easy correction of the error.
```
slang>run hello_world-s.sl
Command failed java.lang.RuntimeException: java.lang.RuntimeException: There was a problem parsing the YAML source: hello_world-s.sl.
while scanning for the next token
found character      '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'string', line 11, column 1:
            ops.print:
    ^
```
