### ISSUE TITLE
python action handling / use of | confusing

### ISSUE THREAD

**Issue by okitac** [openscore/score-language#82]
python actions appear to be parsed as:
(1) Single line of python:
```yaml
      action:
        python_script:  print text
```
(2) Multi-line python:
```yaml
      action:
        python_script: |
            print text
            print text
```
Unfortunately, it seems that:
(1)  The documentation doesn't call out that the use of | is **REQUIRED** for multi-line python scripts
(2)  The documentation doesn't call out that the use of | is **FORBIDDEN** for single-line python scripts

The behaviour is inconsistent and also confusing -- it would be infinitely better to simply have single-line and multi-line python scripts behave in the same way.
